### PR TITLE
htcondor v9.0.16

### PR DESCRIPTION
**Pull request by duncanmmacleod**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@timtheisen, are there any dependency/build changes required?

**Comment by jasoncpatton** [comment]
> @timtheisen, are there any dependency/build changes required?

I'm not aware of any, the diff is pretty small from 9.0.15. We could potentially pin scitokens-cpp > 0.7.1 (FD leak fix), but that seems unnecessary?

**Comment by duncanmmacleod** [comment]
> > @timtheisen, are there any dependency/build changes required?
> 
> I'm not aware of any, the diff is pretty small from 9.0.15. We could potentially pin scitokens-cpp > 0.7.1 (FD leak fix), but that seems unnecessary?

If the upstream packaging declares that, then we should here, but otherwise I'm happy to let the 'user' handle it. AFAIK the FD leak fix is mainly for schedds, and we don't build the daemons here.

**Comment by timtheisen** [comment]
The upstream packaging will declare the minimum version for scitokens-cpp in the next release.

**Review by timtheisen — APPROVED** [review]
LGTM

**Pull request merged**
