### PR TITLE
Enable macOS builds

### PR DESCRIPTION
**Pull request by duncanmmacleod**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@timtheisen, the macOS build always seems to try and downlod http://parrot.cs.wisc.edu/externals/libressl-2.2.7.tar.gz, is there a way to avoid that, presumably by specifying this as a dependency?

**Comment by duncanmmacleod** [comment]
The build here fails with

```
[ 50%] Building CXX object src/condor_utils/CMakeFiles/condor_extra_objects.dir/__/condor_sysapi/idle_time.cpp.o
In file included from /Users/duncan/opt/miniconda3/conda-bld/htcondor-build_1605095133633/work/src/condor_sysapi/idle_time.cpp:42:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:20:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
/opt/MacOSX10.12.sdk/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
        uuid_string_t   ext_jnl_uuid;
        ^
/opt/MacOSX10.12.sdk/usr/include/device/device_types.h:89:16: note: 'io_string_t' declared here
typedef char                    io_string_t[512];
                                ^
In file included from /Users/duncan/opt/miniconda3/conda-bld/htcondor-build_1605095133633/work/src/condor_sysapi/idle_time.cpp:42:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:20:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
/opt/MacOSX10.12.sdk/usr/include/hfs/hfs_format.h:796:20: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
        char            reserved[JIB_RESERVED_SIZE];
                                 ^
/opt/MacOSX10.12.sdk/usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
#define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                            ^
/opt/MacOSX10.12.sdk/usr/include/device/device_types.h:89:16: note: 'io_string_t' declared here
typedef char                    io_string_t[512];
                                ^
In file included from /Users/duncan/opt/miniconda3/conda-bld/htcondor-build_1605095133633/work/src/condor_sysapi/idle_time.cpp:42:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:20:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
In file included from /opt/MacOSX10.12.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
/opt/MacOSX10.12.sdk/usr/include/hfs/hfs_format.h:796:20: error: array is too large (18446744073709551184 elements)
        char            reserved[JIB_RESERVED_SIZE];
                                 ^~~~~~~~~~~~~~~~~
/opt/MacOSX10.12.sdk/usr/include/hfs/hfs_format.h:787:28: note: expanded from macro 'JIB_RESERVED_SIZE'
#define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
make[2]: *** [src/condor_utils/CMakeFiles/condor_extra_objects.dir/build.make:1330: src/condor_utils/CMakeFiles/condor_extra_objects.dir/__/condor_sysapi/idle_time.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2643: src/condor_utils/CMakeFiles/condor_extra_objects.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```

any ideas (@jasoncpatton, @timtheisen)?

**Comment by JaimeFrey** [comment]
The libressl tarball pulled from parrot.cs.wisc.edu is saved under externals/bundles/openssl/1.0.1e/ in the build tree and then extracted there (done in that directory's CMakeLists.txt). You could add the tarball to your source tree and alter the CMakeLists.txt to use that. We only use the include directory from the tarball, so you could reduce the size by omitting everything else.

**Comment by JaimeFrey** [comment]
I don't know what's causing the build failures. I've never seen that before and this set of includes hasn't changed in a long time. It looks like adding an include of <uuid/uuid.h> before the other Darwin-specific includes may help.

**Comment by JaimeFrey** [comment]
I just pushed a change to our master branch to make it easy to avoid the download from parrot.cs.wisc.edu. Now, you just need to place the tarball of libressl 2.2.7 headers files at externals/bundles/openssl/1.0.1e/libressl-2.2.7.tar.gz in the source tree.

**Comment by duncanmmacleod** [comment]
> I just pushed a change to our master branch to make it easy to avoid the download from parrot.cs.wisc.edu. Now, you just need to place the tarball of libressl 2.2.7 headers files at externals/bundles/openssl/1.0.1e/libressl-2.2.7.tar.gz in the source tree.

@JaimeFrey, can you post a link to the relevant commit, then I can include it as a patch in this build?

**Comment by timtheisen** [comment]
Here is a link to the commit that Jaime mentioned: https://github.com/htcondor/htcondor/commit/34611a9cb2f211cdf060ba881e5e88a19c7b4c7c

**Comment by duncanmmacleod** [comment]
> I don't know what's causing the build failures. I've never seen that before and this set of includes hasn't changed in a long time. It looks like adding an include of <uuid/uuid.h> before the other Darwin-specific includes may help.

@jaimefrey, I finally got around to digging into this. The issue is as follows

- htcondor uses `Carbon` on macOS (I don't know why, don't care)
- this leads to importing some `hfs` file system headers which rely upon the `uuid_string_t` object that is seemingly specific to macOS internals
- htcondor relies on `libuuid` on its own, so `conda-forge` brings in its own copy that doesn't have the specific `uuid_string_t` object

I'm working on a way around this.

**Comment by duncanmmacleod** [comment]
> I'm working on a way around this.

Since the conda packages deliberately don't include the daemons (here specifically `condor_startd`) we don't need to build the `sysapi` tools, so can just patch out that part of the cmake configuration. Testing now.

**Review by jasoncpatton — APPROVED** [review]
Looks good! I think your patches will also be useful for the rest of the HTCondor team. I think part of the `libpython` stuff was because of the now-defunct python collector plugin, so we need to get rid of that anyway.

**Pull request merged**
