### PR TITLE
htcondor v9.0.15

### PR DESCRIPTION
**Pull request by duncanmmacleod**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@timtheisen @jasoncpatton the macOS builds are failing with:

```console
In file included from /Users/runner/miniforge3/conda-bld/htcondor-build_1660217934374/work/src/condor_utils/condor_threads.cpp:233:
/Users/runner/miniforge3/conda-bld/htcondor-build_1660217934374/work/src/condor_utils/threads_implementation.h:36:29: error: typedef redefinition with different types ('unsigned long' vs '__darwin_pthread_t' (aka '_opaque_pthread_t *'))
                typedef long unsigned int pthread_t;
                                          ^
/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/sys/_types/_pthread_t.h:30:29: note: previous definition is here
typedef __darwin_pthread_t              pthread_t;
                                        ^
1 error generated.
```

**Comment by duncanmmacleod** [comment]
> 

cmake 3.24.0 removed `CMAKE_HAVE_PTHREAD_H` from `FindThreads`, it's now in `CMakeBackwardsCompatibilityCXX.cmake`. So I am going to pin to `cmake <3.24.0a0` (my preferred no thought solution) until this is fixed upstream. I will open a jira ticket.

**Comment by duncanmmacleod** [comment]
See https://opensciencegrid.atlassian.net/browse/HTCONDOR-1259.

**Comment by duncanmmacleod** [comment]
@timtheisen, @jasoncpatton, I think this is ready to go, any other changes required?

**Review by timtheisen — APPROVED** [review]
LGTM.

**Pull request merged**
